FileNotFoundError in line 59 of /home/users/aheintzbuschart/dadasnake/dada_scripts/get_config.rules:
[Errno 2] File b'/mnt/irisgpfs/users/aheintzbuschart/testdata/samples.small.tsv' does not exist: b'/mnt/irisgpfs/users/aheintzbuschart/testdata/samples.small.tsv'
  File "/home/users/aheintzbuschart/dadasnake/Snakefile", line 7, in <module>
  File "/home/users/aheintzbuschart/dadasnake/dada_scripts/get_config.rules", line 59, in <module>
  File "/home/users/aheintzbuschart/dadasnake/snakemake_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
  File "/home/users/aheintzbuschart/dadasnake/snakemake_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
  File "/home/users/aheintzbuschart/dadasnake/snakemake_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
  File "/home/users/aheintzbuschart/dadasnake/snakemake_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
  File "/home/users/aheintzbuschart/dadasnake/snakemake_env/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
